myapp/urls.py
from django.urls import path
from .views import (BookListView, BookDetailView, BookCreateView, BookUpdateView, BookDeleteView)

app_name = 'myapp'

urlpatterns = [
    path('', BookListView.as_view(), name='book_list'),
    path('<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('create/', BookCreateView.as_view(), name='book_create'),
    path('<int:pk>/update/', BookUpdateView.as_view(), name='book_update'),
    path('<int:pk>/delete/', BookDeleteView.as_view(), name='book_delete'),
]

myapp/models.py
from django.db import models # Expected: Import models from django
from django.utils import timezone # Expected: Import timezone from django with timezone awareness
from django.contrib.auth.models import User #
from django.conf import settings
# Create your models here.
class Author(models.Model): # Expected: Table called Authors class inherits from models.Model
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
    
class Book(models.Model): # Expected: Table called Books class inherits from models.Model
    title = models.CharField(max_length=200)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='books', on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

class Member(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    membership_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.first_name} {self.last_name} (joined {self.membership_date.date()})"
    
class Loan(models.Model):
    members = models.ForeignKey(Member, on_delete=models.CASCADE)
    books = models.ForeignKey(Book, on_delete=models.CASCADE)
    borrow_date = models.DateTimeField(default=timezone.now) 
    return_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.members} currently has {self.books} and was rented on {self.borrow_date.date()} and set to return on {self.return_date.date()}."

myapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Book #import book model from models.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .serializers import BookSerializer, AuthorSerializer
from rest_framework import viewsets, permissions
from .permissions import IsOwnerOrReadOnly

# Create your views here.
class BookListView(LoginRequiredMixin, ListView):
    model = Book
    context_object_name = 'books' # for book in books

class BookDetailView(LoginRequiredMixin, DetailView):
    model = Book

class BookCreateView(LoginRequiredMixin, CreateView):
    model = Book
    fields = ['title', 'author']
    success_url = reverse_lazy('myapp:book_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class BookUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Book
    fields = ['title', 'author']
    template_name = 'myapp/book_form.html'
    success_url = reverse_lazy('myapp:book_list')

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user or self.request.user.is_staff

class BookDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Book
    template_name = 'myapp/book_confirm_delete.html'
    success_url = reverse_lazy('myapp:book_list')

    def test_func(self):
        obj = self.get_object()
        return obj.owner == self.request.user or self.request.user.is_staff

class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all().order_by('id')
    serializer_class = BookSerializer
    permission_classes = [permissions.IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    filterset_fields = ['title', 'author_id'] # Fields for exact matches (e.g., ?field1=value)
    search_fields = ['title'] # Fields for ?search=... parameter
    ordering_fields = ['title', 'id']  # Fields allowed for ?ordering=...
    ordering = ['id'] # Default ordering if not specified by client

    def perform_create(self, serializer):
        serializer.save(owner=self.request.user)

myapp/templates/myapp/book_confirm_delete.html
{% extends 'base_generic.html' %}

{% block title %}Delete Confirmation{% endblock title %}

{% block content %}

    <h2>Banish Book?</h2>
    <p>Confirm you want to banish {{ book.title }}</p>
    <form method="post">
        {% csrf_token %} <!--built-in feature to protect agaisnt csrf attacks-->
        <button type="submit">Banish It!</button>
    </form>
    <br>
    <a href="{% url 'myapp:book_detail' book.pk %}">Nevermind and Go back!</a>
{% endblock content %}

myapp/templates/myapp/book_detail.html
{% extends 'base_generic.html' %}

{% block title %} Book Details {% endblock title %}

{% block content %}
    <h2>{{ book.title }}</h2>
    <h3>Author: {{ book.author }}</h3>
    {% if object.owner == user or user.is_staff %}
        <a href="{% url 'myapp:book_update' book.pk %}">Edit Details</a>
        <a href="{% url 'myapp:book_delete' book.pk %}">Remove Book</a>
    {% endif  %}
    <a href="{% url 'myapp:book_list' %}">Back to the Inventory</a>
{% endblock content %}

myapp/templates/myapp/book_form.html
{% extends 'base_generic.html' %}

{% block title %}Add or Edit Book Details Form{% endblock title %}

{% block content %}
    <h2>Book Add or Edit Form</h2>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Save Data</button>
    </form>
    <br>
    {% if book.pk %}
        <a href="{% url 'myapp:book_detail' book.pk %}">Cancel and Go Back!</a>
    {% else %}
        <a href="{% url 'myapp:book_list' %}">Back to the Inventory</a>
    {% endif %}
{%  endblock content %}

myapp/templates/myapp/book_list.html
{% extends 'base_generic.html' %}

{% block title %} Library Inventory {% endblock title %}

{% block content %}

    <h2>Books in Library</h2>
    <ul>
        {% if user.is_authenticated %}
            <a href="{% url 'myapp:book_create' %}">Donate a book</a>
            {% for book in books %}
            <li>
                <a href="{% url 'myapp:book_detail' book.pk %}"> {{ book.title }}</a>
            </li>
            {% endfor %}
        {% endif %}
    </ul>
{% endblock content %}